	package pourDotNet.entite;
// Generated 2 avr. 2018 22:14:16 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Budgetcrb generated by hbm2java
 */
@Entity
@Table(name = "budgetcrb")
public class Budgetcrb implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private BudgetcrbId id;
	private Comptebudgetaire comptebudgetaire;
	private Crb crb;
	private Exercicebudgetaire exercicebudgetaire;
	private BigDecimal montantinitial;
	private BigDecimal montantengage;
	private BigDecimal montantpreengage;
	private BigDecimal montantdisponible;

	public Budgetcrb() {
	}

	public Budgetcrb(BudgetcrbId id, Comptebudgetaire comptebudgetaire, Crb crb) {
		this.id = id;
		this.comptebudgetaire = comptebudgetaire;
		this.crb = crb;
	}

	public Budgetcrb(BudgetcrbId id, Comptebudgetaire comptebudgetaire, Crb crb, Exercicebudgetaire exercicebudgetaire,
			BigDecimal montantinitial, BigDecimal montantengage, BigDecimal montantpreengage,
			BigDecimal montantdisponible) {
		this.id = id;
		this.comptebudgetaire = comptebudgetaire;
		this.crb = crb;
		this.exercicebudgetaire = exercicebudgetaire;
		this.montantinitial = montantinitial;
		this.montantengage = montantengage;
		this.montantpreengage = montantpreengage;
		this.montantdisponible = montantdisponible;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "numcrb", column = @Column(name = "numcrb", nullable = false, length = 254)),
			@AttributeOverride(name = "numcb", column = @Column(name = "numcb", nullable = false, length = 254)) })
	public BudgetcrbId getId() {
		return this.id;
	}

	public void setId(BudgetcrbId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numcb", nullable = false, insertable = false, updatable = false)
	public Comptebudgetaire getComptebudgetaire() {
		return this.comptebudgetaire;
	}

	public void setComptebudgetaire(Comptebudgetaire comptebudgetaire) {
		this.comptebudgetaire = comptebudgetaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numcrb", nullable = false, insertable = false, updatable = false)
	public Crb getCrb() {
		return this.crb;
	}

	public void setCrb(Crb crb) {
		this.crb = crb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "anneebudg")
	public Exercicebudgetaire getExercicebudgetaire() {
		return this.exercicebudgetaire;
	}

	public void setExercicebudgetaire(Exercicebudgetaire exercicebudgetaire) {
		this.exercicebudgetaire = exercicebudgetaire;
	}

	@Column(name = "montantinitial", precision = 131089, scale = 0)
	public BigDecimal getMontantinitial() {
		return this.montantinitial;
	}

	public void setMontantinitial(BigDecimal montantinitial) {
		this.montantinitial = montantinitial;
	}

	@Column(name = "montantengage", precision = 131089, scale = 0)
	public BigDecimal getMontantengage() {
		return this.montantengage;
	}

	public void setMontantengage(BigDecimal montantengage) {
		this.montantengage = montantengage;
	}

	@Column(name = "montantpreengage", precision = 131089, scale = 0)
	public BigDecimal getMontantpreengage() {
		return this.montantpreengage;
	}

	public void setMontantpreengage(BigDecimal montantpreengage) {
		this.montantpreengage = montantpreengage;
	}

	@Column(name = "montantdisponible", precision = 131089, scale = 0)
	public BigDecimal getMontantdisponible() {
		return this.montantdisponible;
	}

	public void setMontantdisponible(BigDecimal montantdisponible) {
		this.montantdisponible = montantdisponible;
	}

}
