package pourDotNet.entite;
// Generated 2 avr. 2018 22:14:16 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BureauutilisateurId generated by hbm2java
 */
@Embeddable
public class BureauutilisateurId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String numbac;
	private String numutilisateur;

	public BureauutilisateurId() {
	}

	public BureauutilisateurId(String numbac, String numutilisateur) {
		this.numbac = numbac;
		this.numutilisateur = numutilisateur;
	}

	@Column(name = "numbac", nullable = false, length = 254)
	public String getNumbac() {
		return this.numbac;
	}

	public void setNumbac(String numbac) {
		this.numbac = numbac;
	}

	@Column(name = "numutilisateur", nullable = false, length = 254)
	public String getNumutilisateur() {
		return this.numutilisateur;
	}

	public void setNumutilisateur(String numutilisateur) {
		this.numutilisateur = numutilisateur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BureauutilisateurId))
			return false;
		BureauutilisateurId castOther = (BureauutilisateurId) other;

		return ((this.getNumbac() == castOther.getNumbac()) || (this.getNumbac() != null
				&& castOther.getNumbac() != null && this.getNumbac().equals(castOther.getNumbac())))
				&& ((this.getNumutilisateur() == castOther.getNumutilisateur())
						|| (this.getNumutilisateur() != null && castOther.getNumutilisateur() != null
								&& this.getNumutilisateur().equals(castOther.getNumutilisateur())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNumbac() == null ? 0 : this.getNumbac().hashCode());
		result = 37 * result + (getNumutilisateur() == null ? 0 : this.getNumutilisateur().hashCode());
		return result;
	}

}
