package pourDotNet.entite;
// Generated 2 avr. 2018 22:14:16 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comptebudgetaire generated by hbm2java
 */
@Entity
@Table(name = "comptebudgetaire")
public class Comptebudgetaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String numcb;
	private Comptegeneral comptegeneral;
	private String description;
	private String typecompte;
	private Set<Article> articles = new HashSet<Article>(0);
	private Set<Budgetcrb> budgetcrbs = new HashSet<Budgetcrb>(0);

	public Comptebudgetaire() {
	}

	public Comptebudgetaire(String numcb, Comptegeneral comptegeneral) {
		this.numcb = numcb;
		this.comptegeneral = comptegeneral;
	}

	public Comptebudgetaire(String numcb, Comptegeneral comptegeneral, String description, String typecompte,
			Set<Article> articles, Set<Budgetcrb> budgetcrbs) {
		this.numcb = numcb;
		this.comptegeneral = comptegeneral;
		this.description = description;
		this.typecompte = typecompte;
		this.articles = articles;
		this.budgetcrbs = budgetcrbs;
	}

	@Id

	@Column(name = "numcb", unique = true, nullable = false, length = 254)
	public String getNumcb() {
		return this.numcb;
	}

	public void setNumcb(String numcb) {
		this.numcb = numcb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numcg", nullable = false)
	public Comptegeneral getComptegeneral() {
		return this.comptegeneral;
	}

	public void setComptegeneral(Comptegeneral comptegeneral) {
		this.comptegeneral = comptegeneral;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "typecompte", length = 254)
	public String getTypecompte() {
		return this.typecompte;
	}

	public void setTypecompte(String typecompte) {
		this.typecompte = typecompte;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comptebudgetaire")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comptebudgetaire")
	public Set<Budgetcrb> getBudgetcrbs() {
		return this.budgetcrbs;
	}

	public void setBudgetcrbs(Set<Budgetcrb> budgetcrbs) {
		this.budgetcrbs = budgetcrbs;
	}

}
