package pourDotNet.entite;
// Generated 2 avr. 2018 22:14:16 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Comptegeneral generated by hbm2java
 */
@Entity
@Table(name = "comptegeneral")
public class Comptegeneral implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String numcg;
	private Set<Comptebudgetaire> comptebudgetaires = new HashSet<Comptebudgetaire>(0);

	public Comptegeneral() {
	}

	public Comptegeneral(String numcg) {
		this.numcg = numcg;
	}

	public Comptegeneral(String numcg, Set<Comptebudgetaire> comptebudgetaires) {
		this.numcg = numcg;
		this.comptebudgetaires = comptebudgetaires;
	}

	@Id

	@Column(name = "numcg", unique = true, nullable = false, length = 254)
	public String getNumcg() {
		return this.numcg;
	}

	public void setNumcg(String numcg) {
		this.numcg = numcg;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "comptegeneral")
	public Set<Comptebudgetaire> getComptebudgetaires() {
		return this.comptebudgetaires;
	}

	public void setComptebudgetaires(Set<Comptebudgetaire> comptebudgetaires) {
		this.comptebudgetaires = comptebudgetaires;
	}

}
