package pourDotNet.entite;
// Generated 2 avr. 2018 22:14:16 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Demandedeconsommation generated by hbm2java
 */
@Entity
@Table(name = "demandedeconsommation")
public class Demandedeconsommation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numdc;
	private Bureauadministratifcomptable bureauadministratifcomptable;
	private String description;
	private String etat;
	private String objetdemande;
	private String beneficiaire;
	private Date datedemande;
	private Set<Historiquedesbudgets> historiquedesbudgetses = new HashSet<Historiquedesbudgets>(0);
	private Set<Lignedeconsommation> lignedeconsommations = new HashSet<Lignedeconsommation>(0);

	public Demandedeconsommation() {
	}

	public Demandedeconsommation(int numdc, Bureauadministratifcomptable bureauadministratifcomptable) {
		this.numdc = numdc;
		this.bureauadministratifcomptable = bureauadministratifcomptable;
	}

	public Demandedeconsommation(int numdc, Bureauadministratifcomptable bureauadministratifcomptable,
			String description, String etat, String objetdemande, String beneficiaire, Date datedemande,
			Set<Historiquedesbudgets> historiquedesbudgetses, Set<Lignedeconsommation> lignedeconsommations) {
		this.numdc = numdc;
		this.bureauadministratifcomptable = bureauadministratifcomptable;
		this.description = description;
		this.etat = etat;
		this.objetdemande = objetdemande;
		this.beneficiaire = beneficiaire;
		this.datedemande = datedemande;
		this.historiquedesbudgetses = historiquedesbudgetses;
		this.lignedeconsommations = lignedeconsommations;
	}

	@Id

	@Column(name = "numdc", unique = true, nullable = false)
	public int getNumdc() {
		return this.numdc;
	}

	public void setNumdc(int numdc) {
		this.numdc = numdc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numbac", nullable = false)
	public Bureauadministratifcomptable getBureauadministratifcomptable() {
		return this.bureauadministratifcomptable;
	}

	public void setBureauadministratifcomptable(Bureauadministratifcomptable bureauadministratifcomptable) {
		this.bureauadministratifcomptable = bureauadministratifcomptable;
	}

	@Column(name = "description", length = 254)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "etat", length = 254)
	public String getEtat() {
		return this.etat;
	}

	public void setEtat(String etat) {
		this.etat = etat;
	}

	@Column(name = "objetdemande", length = 254)
	public String getObjetdemande() {
		return this.objetdemande;
	}

	public void setObjetdemande(String objetdemande) {
		this.objetdemande = objetdemande;
	}

	@Column(name = "beneficiaire", length = 254)
	public String getBeneficiaire() {
		return this.beneficiaire;
	}

	public void setBeneficiaire(String beneficiaire) {
		this.beneficiaire = beneficiaire;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datedemande", length = 13)
	public Date getDatedemande() {
		return this.datedemande;
	}

	public void setDatedemande(Date datedemande) {
		this.datedemande = datedemande;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demandedeconsommation")
	public Set<Historiquedesbudgets> getHistoriquedesbudgetses() {
		return this.historiquedesbudgetses;
	}

	public void setHistoriquedesbudgetses(Set<Historiquedesbudgets> historiquedesbudgetses) {
		this.historiquedesbudgetses = historiquedesbudgetses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "demandedeconsommation")
	public Set<Lignedeconsommation> getLignedeconsommations() {
		return this.lignedeconsommations;
	}

	public void setLignedeconsommations(Set<Lignedeconsommation> lignedeconsommations) {
		this.lignedeconsommations = lignedeconsommations;
	}

}
