package pourDotNet.entite;
// Generated 2 avr. 2018 22:14:16 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Exercicebudgetaire generated by hbm2java
 */
@Entity
@Table(name = "exercicebudgetaire")
public class Exercicebudgetaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String anneebudg;
	private Date debutexercice;
	private Date finexercice;
	private Integer etatexercice;
	private Set<Budgetcrb> budgetcrbs = new HashSet<Budgetcrb>(0);

	public Exercicebudgetaire() {
	}

	public Exercicebudgetaire(String anneebudg) {
		this.anneebudg = anneebudg;
	}

	public Exercicebudgetaire(String anneebudg, Date debutexercice, Date finexercice, Integer etatexercice,
			Set<Budgetcrb> budgetcrbs) {
		this.anneebudg = anneebudg;
		this.debutexercice = debutexercice;
		this.finexercice = finexercice;
		this.etatexercice = etatexercice;
		this.budgetcrbs = budgetcrbs;
	}

	@Id

	@Column(name = "anneebudg", unique = true, nullable = false, length = 254)
	public String getAnneebudg() {
		return this.anneebudg;
	}

	public void setAnneebudg(String anneebudg) {
		this.anneebudg = anneebudg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "debutexercice", length = 13)
	public Date getDebutexercice() {
		return this.debutexercice;
	}

	public void setDebutexercice(Date debutexercice) {
		this.debutexercice = debutexercice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "finexercice", length = 13)
	public Date getFinexercice() {
		return this.finexercice;
	}

	public void setFinexercice(Date finexercice) {
		this.finexercice = finexercice;
	}

	@Column(name = "etatexercice")
	public Integer getEtatexercice() {
		return this.etatexercice;
	}

	public void setEtatexercice(Integer etatexercice) {
		this.etatexercice = etatexercice;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "exercicebudgetaire")
	public Set<Budgetcrb> getBudgetcrbs() {
		return this.budgetcrbs;
	}

	public void setBudgetcrbs(Set<Budgetcrb> budgetcrbs) {
		this.budgetcrbs = budgetcrbs;
	}

}
