package pourDotNet.entite;
// Generated 2 avr. 2018 22:14:16 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historiquedesbudgets generated by hbm2java
 */
@Entity
@Table(name = "historiquedesbudgets")
public class Historiquedesbudgets implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numhb;
	private Demandedeconsommation demandedeconsommation;
	private Date date;
	private String utilisateur;
	private String action;

	public Historiquedesbudgets() {
	}

	public Historiquedesbudgets(int numhb) {
		this.numhb = numhb;
	}

	public Historiquedesbudgets(int numhb, Demandedeconsommation demandedeconsommation, Date date, String utilisateur,
			String action) {
		this.numhb = numhb;
		this.demandedeconsommation = demandedeconsommation;
		this.date = date;
		this.utilisateur = utilisateur;
		this.action = action;
	}

	@Id

	@Column(name = "numhb", unique = true, nullable = false)
	public int getNumhb() {
		return this.numhb;
	}

	public void setNumhb(int numhb) {
		this.numhb = numhb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "numdc")
	public Demandedeconsommation getDemandedeconsommation() {
		return this.demandedeconsommation;
	}

	public void setDemandedeconsommation(Demandedeconsommation demandedeconsommation) {
		this.demandedeconsommation = demandedeconsommation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 13)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "utilisateur", length = 254)
	public String getUtilisateur() {
		return this.utilisateur;
	}

	public void setUtilisateur(String utilisateur) {
		this.utilisateur = utilisateur;
	}

	@Column(name = "action", length = 254)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

}
