package pourDotNet.entite;
// Generated 2 avr. 2018 22:14:16 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role")
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int numrole;
	private Boolean responsable;
	private Boolean controlleur;
	private Set<Bureauutilisateur> bureauutilisateurs = new HashSet<Bureauutilisateur>(0);

	public Role() {
	}

	public Role(int numrole) {
		this.numrole = numrole;
	}

	public Role(int numrole, Boolean responsable, Boolean controlleur, Set<Bureauutilisateur> bureauutilisateurs) {
		this.numrole = numrole;
		this.responsable = responsable;
		this.controlleur = controlleur;
		this.bureauutilisateurs = bureauutilisateurs;
	}

	@Id

	@Column(name = "numrole", unique = true, nullable = false)
	public int getNumrole() {
		return this.numrole;
	}

	public void setNumrole(int numrole) {
		this.numrole = numrole;
	}

	@Column(name = "responsable")
	public Boolean getResponsable() {
		return this.responsable;
	}

	public void setResponsable(Boolean responsable) {
		this.responsable = responsable;
	}

	@Column(name = "controlleur")
	public Boolean getControlleur() {
		return this.controlleur;
	}

	public void setControlleur(Boolean controlleur) {
		this.controlleur = controlleur;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<Bureauutilisateur> getBureauutilisateurs() {
		return this.bureauutilisateurs;
	}

	public void setBureauutilisateurs(Set<Bureauutilisateur> bureauutilisateurs) {
		this.bureauutilisateurs = bureauutilisateurs;
	}

}
