package pourDotNet.entite;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "utilisateur")
public class Utilisateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String numutilisateur;
	private String nom;
	private String prenom;
	private String adresse;
	private String telephone;
	private String fonction;
	private String email;
	private String login;
	private String password;
	private Set<Bureauutilisateur> bureauutilisateurs = new HashSet<Bureauutilisateur>(0);

	public Utilisateur() {
	}

	public Utilisateur(String numutilisateur) {
		this.numutilisateur = numutilisateur;
	}

	public Utilisateur(String numutilisateur, String nom, String prenom, String adresse, String telephone,
			String fonction, String email, String login, String password, Set<Bureauutilisateur> bureauutilisateurs) {
		this.numutilisateur = numutilisateur;
		this.nom = nom;
		this.prenom = prenom;
		this.adresse = adresse;
		this.telephone = telephone;
		this.fonction = fonction;
		this.email = email;
		this.login = login;
		this.password = password;
		this.bureauutilisateurs = bureauutilisateurs;
	}

	@Id

	@Column(name = "numutilisateur", unique = true, nullable = false, length = 254)
	public String getNumutilisateur() {
		return this.numutilisateur;
	}

	public void setNumutilisateur(String numutilisateur) {
		this.numutilisateur = numutilisateur;
	}

	@Column(name = "nom", length = 254)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 254)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "telephone", length = 254)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fonction", length = 254)
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	@Column(name = "email", length = 254)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "login", length = 254)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 254)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "utilisateur")
	public Set<Bureauutilisateur> getBureauutilisateurs() {
		return this.bureauutilisateurs;
	}

	public void setBureauutilisateurs(Set<Bureauutilisateur> bureauutilisateurs) {
		this.bureauutilisateurs = bureauutilisateurs;
	}

}
